[Interface]
PrivateKey = YJ3xr3BtAxyu3tJF/DvYRJZcpeuEGW+TNiGV7fWYwko=
Address = 10.0.0.2/24
ListenPort = 51820 
MTU = 1280
DNS = 1.1.1.1

[Peer]
PublicKey = JdAyXkCV41CzSThpWzXv7737G4R0YoNiXicS1fgY3Gc=
Endpoint = 44.217.20.52:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
